### ISSUE TITLE
Embedding Files Deleted on Server/Application Restart

### ISSUE THREAD

**Issue by echofire26** [superboki/UNRAID-FR#5]
First, thank you for creating this UnRaid Docker container!

Issue is I'm seeing the embedding files in the embedding folder deleted on server or application restart.  I'm using WebUI 2.  

I'm currently getting around this by keeping a separate backup of all the embedding files and then pasting them back in after restart.

Any assistance or advice would be greatly appreciated.

- Additionally, forgive the ignorance - but where are the folder associations being defined?  Example: VAE, Lora, etc...?

**Comment by grokuku** [comment]
This issue is fixed on the latest version.
Thanks for reporting. :)
All folders for automatic1111 are the default ones, I just replaced models/vae/lora/etc.. folders with symlink that points to the global models folder.
