### ISSUE TITLE
EE micromamba download failed

### ISSUE THREAD

**Issue by UberMetroid** [superboki/UNRAID-FR#6]
Logs:
Downloading micromamba from https://micro.mamba.pm/api/micromamba/linux-64/latest to /opt/stable-diffusion/01-easy-diffusion/installer_files/mamba/micromamba

EE micromamba download failed

Any idea how to fix this?

docker | unraid | easy diffusion

**Comment by grokuku** [comment]
Can you try to remove the folder 01-easy-diffusion, update the container to the latest version, and run the installation again ?

**Comment by UberMetroid** [comment]
Testing now. FYSA, Fooocus is really cool and InvokeAI works well too. Easy-diffusion is the best though because it supports multi-gpu. Ill let you know how the test goes.

**Comment by UberMetroid** [comment]
edit:
Deleted the "01-easy-diffusion" and restarted. It did not work.

Tried again after deleting the entire folder. It is still not downloading.

Also tried directly downloading the file from the source so I could just copy and paste it to the folder... That did not work.

sent 39 bytes  received 12 bytes  102.00 bytes/sec
total size is 0  speedup is 0.00
removing folder /home/diffusion/Stable Diffusion UI and create symlink
/usr/bin/curl
/usr/bin/tar
/usr/bin/bzip2
Downloading micromamba from https://micro.mamba.pm/api/micromamba/linux-64/latest to /opt/stable-diffusion/01-easy-diffusion/installer_files/mamba/micromamba

EE micromamba download failed
EE If the lines above contain 'bzip2: Cannot exec', your system doesn't have bzip2 installed
EE If there are network errors, please check your internet setup

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

ERROR: micromamba download failed

Error downloading Stable Diffusion UI. Sorry about that, please try to:
 1. Run this installer again.
 2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting
 3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB
 4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

Thanks!

**Comment by grokuku** [comment]
I tried to do a new installation from scratch, and it works perfectly fine for me.

If I look at the log you shared, it looks more like a network error than a bug in the installation script (and therefore if it's the case I won't be able to help more)

In doubt, I updated the easy-diffusion install script to the 2.5.41a version. 

You can do a "force update" of the container to be sure you're on latest version, and try again. 

Hope this will help 🤞

**Comment by UberMetroid** [comment]
Thank you for the updated script. However, you were right about the network issue.

Where is https://micro.mamba.pm/api/micromamba/linux-64/latest located at? My network was IP blocking a few countries and when I turned that block off it was able to download it.

**Comment by grokuku** [comment]
Glad you could resovle it :)
